### ISSUE TITLE
Issue compiling

### ISSUE THREAD

**Issue by runrevben** [ggordan/react-infinite-grid#2]
Installing with npm gets the following error message. It seems that various version of React are required however the installation completes. I have installed the latest version of react.

```
npm install react-infinite-grid
npm WARN peerDependencies The peer dependency react@^0.12.0 included from react-infinite-grid will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "react-infinite-grid"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-bootstrap@0.24.0 wants react@>=0.13
npm ERR! peerinvalid Peer react-component-gallery@1.2.1 wants react@*
npm ERR! peerinvalid Peer react-image-grid@0.3.1 wants react@*
npm ERR! peerinvalid Peer react-infinite-grid@0.3.9 wants react@^0.12.0
```

Compiling my code results in an error in the react-infinite-grid

```
browserify -t reactify app.jsx -o build/app.js
Error: Parsing file /Users/ben/Documents/work/websites/sporran_react/node_modules/react-infinite-grid/src/grid.js: Unexpected token (202:12)
    at Deps.parseDeps (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:436:28)
    at fromSource (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:375:44)
    at /usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:369:17
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:129:20)
    at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:199:16)
```

Are you aware of compatibility errors with latest version of React? Perhaps you can point me in the direction to solving this issue.

Thanks for a great looking component.

**Comment by enjoylife** [comment]
npm must be pulling an old version. You could pull directly from github by using:

`npm install https://github.com/ggordan/react-infinite-grid.git`

that should have an updated package.json with the correct react versoin

**Comment by alolis** [comment]
Same issue here.
